# Generated by Django 6.0.4 on 2026-04-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(help_text='e.g. BK-0041', max_length=10, unique=True)),
                ('guest_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('payment_method', models.CharField(choices=[('GCash', 'GCash'), ('Cash on Arrival', 'Cash on Arrival'), ('Credit Card', 'Credit Card')], default='GCash', max_length=20)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Checked In', 'Checked In'), ('Pending', 'Pending'), ('Checked Out', 'Checked Out')], default='Pending', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.room')),
            ],
        ),
    ]
